"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowRight, BarChart3, BrainCircuit, Check, ChevronDown, FileText, Layers3, Megaphone, Search, Sparkles, Zap } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useState } from "react";


const reveal = { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.2 }, transition: { duration: 0.55 } };

type Feature = { id: string; icon: LucideIcon; title: string; copy: string };
type Agent = { id: string; icon: LucideIcon; name: string; description: string };
type ListItem = { id: string; label: string };
type Faq = { id: string; question: string; answer: string };

const features: Feature[] = [
  { id: "strategic-clarity", icon: BrainCircuit, title: "Strategic clarity", copy: "Turn scattered thoughts into a focused strategy with a co-founder who sees the whole board." },
  { id: "momentum-on-demand", icon: Zap, title: "Momentum on demand", copy: "Go from a question to an executable plan without losing a day to context switching." },
  { id: "everything-connected", icon: Layers3, title: "Everything connected", copy: "Your research, decisions, and assets live in one intelligent, living workspace." },
];

const agents: Agent[] = [
  { id: "research-agent", icon: Search, name: "Research Agent", description: "Maps markets, customers, and your sharpest opportunity." },
  { id: "growth-agent", icon: Megaphone, name: "Growth Agent", description: "Finds your voice and turns attention into traction." },
  { id: "ops-agent", icon: FileText, name: "Ops Agent", description: "Transforms decisions into documents, systems, and next steps." },
];

const momentumBars = [
  { id: "momentum-1", height: 34 }, { id: "momentum-2", height: 48 }, { id: "momentum-3", height: 43 }, { id: "momentum-4", height: 61 },
  { id: "momentum-5", height: 57 }, { id: "momentum-6", height: 78 }, { id: "momentum-7", height: 92 },
];
const dashboardInsights: ListItem[] = [
  { id: "agent-insights", label: "3 agent insights" }, { id: "tasks-complete", label: "7 tasks complete" }, { id: "ideas-captured", label: "12 ideas captured" },
];
const documentSections: ListItem[] = [
  { id: "opportunity", label: "The opportunity" }, { id: "why-now", label: "Why now" }, { id: "unfair-advantage", label: "Our unfair advantage" },
];
const documents: ListItem[] = [
  { id: "investor-narrative", label: "Investor narrative" }, { id: "customer-discovery-brief", label: "Customer discovery brief" }, { id: "launch-plan", label: "90-day launch plan" },
];
const faqs: Faq[] = [
  { id: "what-is-foundergpt", question: "What is FounderGPT X?", answer: "FounderGPT X is an AI operating system for early-stage founders. It combines a shared company memory with specialist AI agents to help you think, decide, and execute." },
  { id: "technical-requirements", question: "Do I need to be technical?", answer: "Not at all. FounderGPT X is built for clear thinking and action, whether you are writing your first brief or scaling an experienced team." },
  { id: "company-privacy", question: "Will my company information stay private?", answer: "Yes. Your workspace is private by default and we use industry-standard controls to protect your information." },
  { id: "team-collaboration", question: "Can I bring my team?", answer: "Absolutely. Start solo, then invite collaborators when you are ready to build a shared operating rhythm." },
];

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="mb-4 text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">{children}</p>; }
function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: React.ReactNode; copy: string }) { return <motion.div {...reveal} className="mx-auto max-w-2xl text-center"><Eyebrow>{eyebrow}</Eyebrow><h2 className="text-balance text-3xl font-semibold tracking-[-0.045em] text-white sm:text-5xl">{title}</h2><p className="mt-5 text-pretty leading-7 text-slate-400">{copy}</p></motion.div>; }

export function Features() { return <section id="features" className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><SectionHeading eyebrow="Built for the messy middle" title={<>Less busywork. More <span className="gradient-text">breakthroughs.</span></>} copy="FounderGPT X brings the leverage of a complete founding team into a single, beautifully calm workspace." /><div className="mt-12 grid gap-4 md:grid-cols-3">{features.map((item, index) => { const Icon = item.icon; return <motion.article key={item.id} {...reveal} transition={{ duration: 0.5, delay: index * 0.08 }} className="glass rounded-2xl p-6 transition hover:-translate-y-1 hover:border-cyan-300/25"><span className="grid size-10 place-items-center rounded-xl bg-cyan-300/10 text-cyan-200"><Icon className="size-5" /></span><h3 className="mt-6 text-lg font-medium text-white">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{item.copy}</p></motion.article>; })}</div></div></section>; }

export function Agents() { return <section id="agents" className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><motion.div {...reveal}><Eyebrow>Your AI founding team</Eyebrow><h2 className="text-balance text-3xl font-semibold tracking-[-0.045em] text-white sm:text-5xl">Specialists that share your <span className="gradient-text">context.</span></h2><p className="mt-5 max-w-md leading-7 text-slate-400">Each agent is an expert in its lane. Together, they operate from the same memory—so nothing gets lost between a big decision and its execution.</p><a href="#dashboard" className="mt-8 inline-flex items-center gap-2 text-sm font-medium text-cyan-200 hover:text-white">Meet your agents <ArrowRight className="size-4" /></a></motion.div><div className="grid gap-3">{agents.map((item, index) => { const Icon = item.icon; return <motion.div key={item.id} {...reveal} transition={{ duration: .5, delay: index * .1 }} className="glass flex items-center gap-4 rounded-2xl p-4 sm:p-5"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-violet-400/20 to-cyan-300/20 text-cyan-100"><Icon className="size-5" /></span><div><h3 className="font-medium text-white">{item.name}</h3><p className="mt-1 text-sm text-slate-400">{item.description}</p></div><span className="ml-auto size-2 shrink-0 rounded-full bg-emerald-400 shadow-[0_0_12px_#34d399]" /></motion.div>; })}</div></div></section>; }

export function DashboardPreview() { return <section id="dashboard" className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><SectionHeading eyebrow="Your command center" title="See the signal. Move with confidence." copy="A single source of truth for your company, designed to make the next best move obvious." /><motion.div {...reveal} className="glass relative mt-12 overflow-hidden rounded-2xl p-2 shadow-2xl shadow-cyan-950/30"><div className="rounded-xl border border-white/[0.06] bg-[#0a1021] p-4 sm:p-6"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs text-slate-500">Good morning, Alex</p><h3 className="mt-1 text-xl font-medium text-white">Your founder brief</h3></div><span className="rounded-full bg-cyan-300/10 px-3 py-1 text-xs text-cyan-200">Thursday, 18 July</span></div><div className="grid gap-4 lg:grid-cols-[1.4fr_.9fr]"><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4 sm:p-5"><div className="flex items-center gap-2 text-sm font-medium text-slate-200"><Sparkles className="size-4 text-cyan-300" /> Focus for today</div><p className="mt-4 max-w-lg text-sm leading-6 text-slate-300">Validate onboarding friction with five new interviews before finalizing the activation sequence.</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-md bg-violet-400/10 px-2.5 py-1 text-xs text-violet-200">Customer research</span><span className="rounded-md bg-white/5 px-2.5 py-1 text-xs text-slate-400">High impact</span></div></div><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><div className="flex items-center gap-2 text-sm text-slate-300"><BarChart3 className="size-4 text-emerald-300" /> Weekly momentum</div><div className="mt-5 flex h-20 items-end gap-2">{momentumBars.map((item) => <span key={item.id} style={{ height: `${item.height}%` }} className="flex-1 rounded-t bg-gradient-to-t from-cyan-500/30 to-cyan-300" />)}</div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{dashboardInsights.map((item) => <div key={item.id} className="rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-3 text-xs text-slate-400">{item.label}</div>)}</div></div></motion.div></div></section>; }

export function Documents() { return <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-2"><motion.div {...reveal} className="order-2 lg:order-1"><div className="glass rounded-2xl p-4"><div className="rounded-xl bg-white/[0.025] p-5 sm:p-7"><div className="flex items-center gap-3 border-b border-white/[0.07] pb-5"><span className="grid size-9 place-items-center rounded-lg bg-violet-400/15 text-violet-200"><FileText className="size-4" /></span><div><p className="text-sm font-medium text-white">Investor narrative</p><p className="text-xs text-slate-500">Generated 2 min ago</p></div><span className="ml-auto text-xs text-emerald-300">Ready</span></div><p className="mt-6 text-lg font-medium tracking-[-.02em] text-slate-100">A new kind of operating system for the people building what&apos;s next.</p><div className="mt-5 space-y-3">{documentSections.map((item) => <div key={item.id} className="flex items-center gap-3 text-sm text-slate-400"><Check className="size-4 text-cyan-300" /> {item.label}</div>)}</div></div></div></motion.div><motion.div {...reveal} className="order-1 lg:order-2"><Eyebrow>From thought to artifact</Eyebrow><h2 className="text-balance text-3xl font-semibold tracking-[-.045em] text-white sm:text-5xl">Work that&apos;s already <span className="gradient-text">in your voice.</span></h2><p className="mt-5 max-w-lg leading-7 text-slate-400">Give your agents a thought, a note, or a conversation. Get polished work you can use, edit, and share—with the reasoning that got you there.</p><div className="mt-7 space-y-3">{documents.map((item) => <div key={item.id} className="flex items-center gap-3 text-sm text-slate-300"><FileText className="size-4 text-violet-300" /> {item.label}</div>)}</div></motion.div></div></section>; }

export function FAQ() { const [open, setOpen] = useState(0); return <section id="faq" className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-3xl"><SectionHeading eyebrow="Questions, answered" title="A calmer way to build." copy="Everything you need to know before you meet your new founding team." /><div className="mt-10 divide-y divide-white/[0.08] border-y border-white/[0.08]">{faqs.map((item, index) => <div key={item.id}><button onClick={() => setOpen(open === index ? -1 : index)} className="flex w-full items-center justify-between gap-4 py-5 text-left text-sm font-medium text-white" aria-expanded={open === index}>{item.question}<ChevronDown className={`size-4 text-slate-400 transition ${open === index ? "rotate-180" : ""}`} /></button>{open === index && <p className="max-w-2xl pb-5 text-sm leading-6 text-slate-400">{item.answer}</p>}</div>)}</div></div></section>; }

export function CTA() { return <section id="cta" className="px-5 pb-24 pt-12 sm:px-8"><motion.div {...reveal} className="relative mx-auto max-w-6xl overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-violet-500/20 via-slate-950 to-cyan-500/15 px-6 py-16 text-center sm:px-12 sm:py-20"><div className="glow glow-cyan -bottom-32 left-1/3 opacity-50" /><div className="relative"><Eyebrow>Make today count</Eyebrow><h2 className="mx-auto max-w-3xl text-balance text-4xl font-semibold tracking-[-.055em] text-white sm:text-6xl">Your next chapter starts with a better first move.</h2><p className="mx-auto mt-5 max-w-xl text-slate-400">Join the founders building with more clarity, focus, and momentum.</p><Link href="/signup" className="mt-8 inline-flex h-12 items-center gap-2 rounded-xl bg-white px-5 font-semibold text-slate-950 hover:bg-cyan-50">Start building free <ArrowRight className="size-4" /></Link><p className="mt-4 text-xs text-slate-500">No credit card required</p></div></motion.div></section>; }

export function Footer() { return <footer className="border-t border-white/[0.07] px-5 py-10 sm:px-8"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p className="font-semibold tracking-[-.04em] text-white">FounderGPT <span className="text-cyan-300">X</span></p><p className="mt-2 text-xs text-slate-500">The operating system for ambitious founders.</p></div><div className="flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500"><a href="#features" className="hover:text-white">Product</a><a href="#faq" className="hover:text-white">FAQ</a><a href="#" className="hover:text-white">Privacy</a><a href="#" className="hover:text-white">Terms</a></div><p className="text-xs text-slate-600">© 2026 FounderGPT X</p></div></footer>; }
